

 drop table authorities if exists;  
drop table users if exists;

create table users(
    username varchar_ignorecase(50) not null primary key,
    password varchar_ignorecase(500) not null,
    enabled boolean not null
);


create table authorities (
    username varchar_ignorecase(50) not null,
    authority varchar_ignorecase(50) not null,
    constraint fk_authorities_users foreign key(username) references users(username)
);
create unique index ix_auth_username on authorities (username,authority);

/*  Bcrypt password   */
/*
insert into users (username,password,enabled)  values('nuser','$2a$11$Uqva8HvRUA4lfSDXMV0nI.Wuw6sIMEIxbD/QG2vlwla8buHoBUNTe',1);
insert into users (username,password,enabled)  values('auser','$2a$11$Uqva8HvRUA4lfSDXMV0nI.Wuw6sIMEIxbD/QG2vlwla8buHoBUNTe',1);
*/
/* Sha with salted hash password  */
insert into users (username,password,enabled)  values('nuser','73676a3b3d262a2c1f914ac18e18c1fcd969cafed9521aa71f3572f9b671ac1a280a29e13bee3613',1);
insert into users (username,password,enabled)  values('auser','0c9cbc5bb09a272577d5f7eb9731fc8a8091b53dbd439cf50cc856bf7c6407544aeb151414863e6f',1);

/* insert into authorities(username,authority) values('nuser','ROLE_FOO');  */

/* Group Based Access Control */

drop table group_members if exists;
drop table group_authorities if exists;
drop table groups if exists;

create table groups (
    id bigint generated by default as identity(start with 0) primary key,
    group_name varchar_ignorecase(50) not null
);

create table group_authorities (
    group_id bigint not null,
    authority varchar(50) not null,
    constraint fk_group_authorities_group foreign key(group_id) references groups(id)
);

create table group_members (
    id bigint generated by default as identity(start with 0) primary key,
    username varchar(50) not null,
    group_id bigint not null,
    constraint fk_group_members_group foreign key(group_id) references groups(id)
);

insert into groups (id,group_name) values(1,'Admin');
insert into groups (id,group_name) values(2,'User');

insert into group_authorities (group_id,authority) values (1,'ROLE_FOO');
insert into group_authorities (group_id,authority) values (2,'ROLE_USER');

insert into group_members (id,username,group_id) values (1,'nuser',1);
insert into group_members (id,username,group_id) values (2,'auser',2);

